language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
- 2.1.5
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: "XiN5V42DSn3B9uvPg2BkC8T7c9RiFzLSJPJVEJi53c2PAhxR7lDlTufHshfWP2wAItXsey/6wCKGNVWI/TtNUxN4fy6ZL4/jf/uw2uVc648OPw+9qk1C4jn3WMVUyIkDb9CPIOVCM6+t5Bu9pT0Hwandv//vqdZlmr/DoGio5O5Etd417fd8//B8Trud2s5QijQhvaCmRxihFbCAKmkegl0oT9uzlhwDCBwTwuh2t+BG33RqZCejWb9wmzzuRefuTULXBvwHYHFLohzXB8PpW8CJvD5yQsKbuYObskGpBaaTOds/qJM2Q39BMTk05Mmz5FFCLZU6JJBniZGg5En+kCW3keVlA03f1ubgjdF7X3ayyOMosBzxHh1KHk1IvNmxnYRae5OBvGS1pWkhlmH1IZbLx6IX8+lx31NC6GQhLYXc6CReziLiYr42tP3JxO9vdGGVo52Fhu06xAl3qTJiY0V5LQbE/9y0Ip0PzWvdeFGBYlPPSXuFaXDSJ44tn7QLjHGkmwlF2YrKrxzFOJq1mE5RHPjHzZFzkMmSA9OBO/uGuCPR2+riz40LvIihhXp9QVKNE9kk5vF/7BwIbwQI3kytYAnWuwCHgbONsAbR03UqWogH0ZUo3s7IyosENnOtvEvjoAv/e+JCgANxvLDOYTu6cBDtmhjXczFUgx7VH5E="
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
